export const CONFIG = {
  canvasWidth: 1280,
  canvasHeight: 720,
  stageLength: 12500,
  groundY: 620,
  gravity: 1150,
  camera: {
    followStartX: 520,
    followEndX: 760,
    minX: 0,
    smoothing: 1,
  },
  player: {
    width: 120,
    height: 120,
    moveSpeed: 340,
    verticalMoveSpeed: 260,
    dragMoveSpeed: 620,
    dragDeadZone: 12,
    touchAssistRadius: 260,
    touchAssistTargetDistance: 230,
    minScreenX: 120,
    maxScreenX: 900,
    startScreenX: 220,
    startWorldX: 220,
    minWorldX: 80,
    maxWorldX: 12100,
    allowBacktracking: true,
    y: 255,
    minY: 220,
    maxY: 390,
    verticalMovementEnabled: true,
    dragVerticalDeadZone: 10,
  },
  water: {
    intervalMs: 240,
    horizontalSpeed: 285,
    initialVerticalSpeed: 88,
    gravity: 500,
    width: 24,
    height: 24,
    nozzleOffsetX: 62,
    nozzleOffsetY: 18,
    maxActiveDrops: 20,
  },
  wateringCan: {
    maxWater: 50,
    initialWater: 25,
    refillAmount: 10,
    refillCost: 100,
  },
  timer: {
    enabled: true,
    timeLimitSeconds: 180,
    warningThresholdSeconds: 30,
  },
  frog: {
    detectionRange: 700,
    moveSpeed: 120,
    waterSuctionRange: 260,
    requiredWaterForFull: 10,
    rewards: {
      none: 0.4,
      water: 0.25,
      points: 0.2,
      mediumFlower: 0.1,
      largeFlower: 0.05,
    },
    waterRewardAmount: 5,
    pointRewardAmount: 50,
    flowerSpawnOffsetX: 350,
  },
  bird: {
    warningDurationMs: 1000,
    speed: 380,
    collisionWaterLoss: 5,
    invincibilityMs: 1200,
  },
  flowerDensity: {
    minimumVisibleTarget: 3,
    denseVisibleTarget: 8,
  },
  ui: {
    lowWaterThreshold: 10,
    refillAnimationMs: 700,
    emptyFeedbackCooldownMs: 500,
    messageMs: 900,
  },
  flowerAnimation: {
    hitDurationMs: 190,
    hitBouncePx: 4,
    bloomDurationMs: 190,
    bloomScale: 1.18,
    particleCount: 5,
    chainWindowMs: 1200,
    chainPitchStep: 34,
  },
  flower: {
    small: {
      requiredWater: 1,
      score: 30,
      width: 56,
      height: 68,
      hitboxWidth: 28,
      hitboxHeight: 24,
      hitboxOffsetX: 14,
      hitboxOffsetY: 4,
    },
    medium: {
      requiredWater: 3,
      score: 40,
      width: 82,
      height: 96,
      hitboxWidth: 42,
      hitboxHeight: 34,
      hitboxOffsetX: 20,
      hitboxOffsetY: 8,
    },
    large: {
      requiredWater: 6,
      score: 120,
      width: 116,
      height: 132,
      hitboxWidth: 62,
      hitboxHeight: 48,
      hitboxOffsetX: 27,
      hitboxOffsetY: 10,
    },
  },
  stage: {
    transitionDistance: 1000,
  },
  debug: {
    enabled: false,
    showHitboxes: false,
    showMetrics: false,
  },
  goalX: 12100,
  assetManifestUrl: "./src/asset_manifest.js",
};
